name: run
on:
  workflow_dispatch:
  push:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:   
      - name: run
        run: sudo apt update && sudo apt install expect xrdp ssh && sudo swapoff -a && sudo rm -rf /mnt/swap* /usr/share/dotnet /usr/share/swift /usr/local/lib/android /opt/ghc /usr/local/.ghcup /usr/local/share/boost "$AGENT_TOOLSDIRECTORY" /opt/hostedtoolcache/ /usr/local/graalvm/ /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules && sudo docker image prune --all --force && printf "root\nroot" | sudo passwd root && printf "root" | su - root -c " curl https://raw.githubusercontent.com/amitstudydude/guacamole/main/run | sudo bash " 
